services:
  flask_app:
    build: .
    ports:
      - "80:80"
      # 5000 is already used in Mac
    volumes:
      - ./api:/var/www/html/arch-struct-analysis/api
      - ./frontend:/var/www/html/arch-struct-analysis/frontend
