version: '3.8'
services:
  php-frontend:
    build:
      context: ./architectual-structural-analysis-frontend/
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
      # for local env
    depends_on:
      - flask-api

  flask-api:
    build:
      context: ./architectual-structural-analysis-api/
      dockerfile: Dockerfile.web
    ports:
      - "5001:5000"
      # for local env
      # 5000 is used in Mac
