services:
  flask_app:
    build: .
    ports:
      - "80:80"
      # - "5001:5001"
      # 5000 is used in Mac
    volumes:
      - ./api:/var/www/my_flask_app/api
      - ./frontend:/var/www/my_flask_app/frontend
