# FROM python:3.8-slim
FROM --platform=linux/amd64 python:3.8-slim
# Heroku needs AMD64 version

WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
CMD ["python", "app.py"]


# yasuhiro@YasuhironoMacBook-Pro architectural-structural-analysis % heroku container:login

# Login Succeeded
# yasuhiro@YasuhironoMacBook-Pro architectural-structural-analysis % heroku container:push --recursive --app pure-journey-37437

# ? Found multiple Dockerfiles with process type web. Please choose one to build and push  
# /Users/yasuhiro/github.com/yasuhiro112358/architectural-structural-analysis/flask/Dockerfile.web
# === Building web (/Users/yasuhiro/github.com/yasuhiro112358/architectural-structural-analysis/flask/Dockerfile.web)
# [+] Building 3.6s (9/9) FINISHED                                                                                                           docker:desktop-linux
#  => [internal] load build definition from Dockerfile.web                                                                                                   0.0s
#  => => transferring dockerfile: 4.06kB                                                                                                                     0.0s
#  => [internal] load metadata for docker.io/library/python:3.8-slim                                                                                         0.8s
#  => [internal] load .dockerignore                                                                                                                          0.0s
#  => => transferring context: 2B                                                                                                                            0.0s
#  => [1/4] FROM docker.io/library/python:3.8-slim@sha256:2f911e2866173a52104dc16b5e42b7069c2eba05eb78556d18b1ca665d0dc445                                   0.0s
#  => [internal] load build context                                                                                                                          0.0s
#  => => transferring context: 4.25kB                                                                                                                        0.0s
#  => CACHED [2/4] WORKDIR /app                                                                                                                              0.0s
#  => [3/4] COPY . /app                                                                                                                                      0.0s
#  => [4/4] RUN pip install -r requirements.txt                                                                                                              2.7s
#  => exporting to image                                                                                                                                     0.1s
#  => => exporting layers                                                                                                                                    0.0s
#  => => writing image sha256:32fa273cd4ae8b69583e52f81c997bef75beb1b43367fe3429efdc1c4e43e841                                                               0.0s
#  => => naming to registry.heroku.com/pure-journey-37437/web                                                                                                0.0s

# What's Next?
#   View a summary of image vulnerabilities and recommendations → docker scout quickview
# === Pushing web (/Users/yasuhiro/github.com/yasuhiro112358/architectural-structural-analysis/flask/Dockerfile.web)
# Using default tag: latest
# The push refers to repository [registry.heroku.com/pure-journey-37437/web]
# 070378c48f91: Pushed 
# 9ae7c4c320f0: Pushed 
# 685e01944866: Pushed 
# b60a1f471434: Pushed 
# 8d8e7f754ef8: Pushed 
# cbb0bec46633: Pushed 
# 7a75d57a5024: Pushed 
# 52ec5a4316fa: Pushed 
# latest: digest: sha256:6758b80783fbe17e232a71f622b6a34c43fb84609bb9f5544df020ae6b407a1d size: 1995
# Your image has been successfully pushed. You can now release it with the 'container:release' command.

# ==================

# yasuhiro@YasuhironoMacBook-Pro architectural-structural-analysis % heroku container:release web --app pure-journey-37437
# Releasing images web to pure-journey-37437... done

# ==================

# yasuhiro@YasuhironoMacBook-Pro architectural-structural-analysis % heroku open --app pure-journey-37437