# FROM php:7.4-apache
FROM --platform=linux/amd64 php:7.4-apache
# Heroku needs AMD64 version

# Copy all PHP files
COPY ./ /var/www/html/

# Change permission for uploads dir
RUN mkdir -p /var/www/html/uploads && \
    chown -R www-data:www-data /var/www/html/uploads && \
    chmod -R 755 /var/www/html/uploads